
GET http://localhost:3001/api/persons/

### 
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Otra Salleh",
  "number": "69-42-667"
}

###
GET http://localhost:3001/api/persons/65203de9e5490024a8d3c300

###
DELETE http://localhost:3001/api/persons/65203d9ce5490024a8d3c2fe

### 
PUT http://localhost:3001/api/persons/652051c4087f46eccd5d9b27
Content-Type: application/json

{
  "name": "Max Verstappen",
  "number": "2"
}